apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260517-224620-afts1gvu6fdm-service
spec:
  selector:
    app: enterprise-system-20260517-224620-afts1gvu6fdm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
